layout_spectrum: 0.09634951572311987
typography_spectrum: 0.6469069833227313
color:
  lightness: 0.4717336860926139
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  saturation: 0.07116811441442017
  brandStrength: 0.9195337291368016
  rhythmicContrast: 0.9456908053535008
coverPrefs:
  filter: false
name: Moreno Consulting
analytics: {}
purpose:
  - type: contact
    url: 'mailto:info@daas.com'
    label: Contact us
github: true
description: 'AI, Machine learning, Data Science, and Cyber Security'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
navigation:
  - id: fb57aa08-6453-4ded-aa30-8e82fdaa743d
    name: Blog
    type: content
content_rating:
  adult: false
opengraph: {}
title: Los Angeles Consulting
url: 'https://thegrid.ai/moreno-consulting/'
